# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4c666fe618b82684c28991fa1ee41c2cb5fe88f84af1b30b3f9f8fcb0b52168f4415e2fab311eefe3dc05e4609977da0e0e2d510c3c860269f404cb9b38fd36

test:
  secret_key_base: be1538dca43a47be19d1efb83eb0b7cf45ee3eb1a6a838af0cbb735b3692abcd327c232226dd7a7a4b0d21de40a26d57946b907b3ce81b73ced8c1a518a61cbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
